### ISSUE TITLE
Write updated version of OSTree docs

### ISSUE THREAD

**Issue by msehnout** [osbuild/guides#31]
Missing sections:
 * building containes, importing into podman, using them
 * building installers, their usage

@achilleas-k or @gicmo would you like to write it?

**Comment by msehnout** [comment]
The notes you have for the presentation should be good enough starting point, I could continue on top of them :-)

**Comment by achilleas-k** [comment]
yeah I can clean up my demo notes and add them as a guide

**Comment by msehnout** [comment]
Thanks! Feel free to keep it concise, I can expand it myself.

**Comment by achilleas-k** [comment]
Opened PR #32
